#!/bin/bash
source /etc/os-release
VIMRC="$HOME/.vimrc"
VIM_FOLDER="$HOME/.vim"
BACKUP_SUFFIX="ct.old"

# folder where to link vim plugins installed from debian package
VIM_LINK_FOLDER="$VIM_LINK_FOLDER/"

# language servers to install
LANG_SERVERS="shellcheck gopls"

# dependencies that can be removed after uninstall
OPT_DEPS="tmux fzf ripgrep vim-ale"

# vital dependencies
DEPS="stow gawk vim git $OPT_DEPS"

unlink_files(){ dir="$1"
  dir_name="$2"
  ls $dir | while read file; do
  rm -f "$VIM_LINK_FOLDER/$dir_name/$file"
done
}

# ROOT FUNCTIONS
install_deps(){
  [[ "$(whoami)" != "root" ]] && echo "run $0 as root" && exit 1
  case $ID in
    "arch")
      pacman -S $DEPS --noconfirm
      ;;
    "debian"|"ubuntu")
      apt install $DEPS -y
      # installing fzf vim integration
      mkdir -p "$VIM_LINK_FOLDER/plugin/" && ln -fs "/usr/share/doc/fzf/examples/plugin/fzf.vim" "$VIM_LINK_FOLDER/plugin/"
      # installing vim-ale vim integration
      mkdir -p "$VIM_LINK_FOLDER/autoload/" && ln -fs /usr/share/vim-ale/autoload/* "$VIM_LINK_FOLDER/autoload"
      mkdir -p "$VIM_LINK_FOLDER/syntax/" && ln -fs /usr/share/vim-ale/syntax/* "$VIM_LINK_FOLDER/syntax"
      mkdir -p "$VIM_LINK_FOLDER/ftplugin/" && ln -fs /usr/share/vim-ale/ftplugin/* "$VIM_LINK_FOLDER/ftplugin"
      mkdir -p "$VIM_LINK_FOLDER/rplugin/" && ln -fs /usr/share/vim-ale/rplugin/* "$VIM_LINK_FOLDER/rplugin"
      mkdir -p "$VIM_LINK_FOLDER/ale_linters/" && ln -fs /usr/share/vim-ale/ale_linters/* "$VIM_LINK_FOLDER/ale_linters"
      ;;
  esac
}

install_language_servers(){
  [[ "$(whoami)" != "root" ]] && echo "run $0 as root" && exit 1
  case $ID in
    "arch")
      pacman -S $LANG_SERVERS --noconfirm
      ;;
    "debian"|"ubuntu")
      apt install $LANG_SERVERS -y
      ;;
  esac
}

uninstall_deps_language_servers(){
  [[ "$(whoami)" != "root" ]] && echo "run $0 as root" && exit 1
  case $ID in
    "arch")
      pacman -Rns $OPT_DEPS $LANG_SERVERS --noconfirm
      ;;
    "debian"|"ubuntu")
      rm -r "$VIM_LINK_FOLDER/plugin/fzf.vim"
      unlink_files /usr/share/vim-ale/autoload autoload
      unlink_files /usr/share/vim-ale/ftplugin ftplugin
      unlink_files /usr/share/vim-ale/rplugin rplugin
      unlink_files /usr/share/vim-ale/syntax syntax
      unlink_files /usr/share/vim-ale/ale_linters ale_linters
      apt remove $OPT_DEPS $LANG_SERVERS -y
      ;;
  esac
}

# USER FUNCTIONS
function install_toolbox(){
  # backup .vimrc than if stow fails backup .vim folder and try again
  if [[ -f "$VIMRC" ]]; then
    echo "backup vimrc file"
    mv "$VIMRC" "$VIMRC.$BACKUP_SUFFIX"
  fi
  if ! stow vim; then
    if [[ -d "$VIM_FOLDER" ]]; then
      echo "backup .vim directory"
      mv "$VIM_FOLDER" "$VIM_FOLDER.$BACKUP_SUFFIX"
    fi
    stow vim
  fi

  # editing PATH variable and sourcing shell integration
  if [[ "$(grep 'toolbox/bash_integration' "$HOME/.bashrc" )" == "" ]]; then
    echo "adding toolbox bash integration"
    echo "source $(pwd)/bash_integration.sh" >> "$HOME/.bashrc"
  fi
  if [[ "$(grep 'toolbox/bin' "$HOME/.bashrc" )" == "" ]]; then
    echo "adding toolbox bins to path"
    echo "export PATH=\$PATH:$(pwd)/bin" >> "$HOME/.bashrc"
  fi
}

function uninstall_toolbox(){
  echo "removing config with stow"
  stow -D vim
  if [[ -f "$VIMRC.$BACKUP_SUFFIX" ]]; then
    echo "restoring old vimrc"
    mv "$VIMRC.$BACKUP_SUFFIX" "$VIMRC"
  fi
  if [[ -d "$VIM_FOLDER.$BACKUP_SUFFIX" ]]; then
    echo "restoring old .vim";
    mv "$VIM_FOLDER.$BACKUP_SUFFIX" "$VIM_FOLDER";
  fi
  echo "removing lines from bashrc"
  sed -i 's/.*toolbox.*//g' "$HOME/.bashrc"
}


COMMAND="$1"
case "$COMMAND" in
  "install_toolbox")
    install_toolbox
    ;;
  "uninstall_toolbox")
    uninstall_toolbox
    ;;
  "install_language_servers")
    install_language_servers
    ;;
  "install_deps")
    install_deps
    ;;
  "uninstall_deps_language_servers")
    uninstall_deps_language_servers
    ;;
  "help"|"--help")
    echo "usage $0 [install_toolbox|uninstall_toolbox|install_language_servers|install_deps|uninstall_deps_language_servers]"
    echo "to install from scratch run:"
    echo "$0 install_deps"
    echo "$0 install_toolbox"
    ;;
  'uninstall')
    # if not running as root call deps nstallation with sudo
    if [[ "$(whoami)" != "root" ]]; then
      echo "installing deps and toolbox"
      sudo "$0" uninstall_deps_language_servers && uninstall_toolbox
    else
      "$0" uninstall_deps_language_servers && uninstall_toolbox
    fi
    ;;
  *)
    # if not running as root call deps installation with sudo
    if [[ "$(whoami)" != "root" ]]; then
      echo "installing deps and toolbox"
      sudo "$0" install_deps && install_toolbox
    else
      "$0" install_deps && install_toolbox
    fi
    ;;
esac
